configfile: "../config/config.yaml"

rule all:
    input:
        "all_genes.trimmed.aln.phy.raxml.support.midpoint_rooted",
        "all_genes.trimmed.aln.phy.raxml.support.midpoint_rooted.svg"

rule concatenate:
    output: all_fasta="all_genes.fasta"
    shell: "cat *.fa* > {output.all_fasta}"


rule mafft:
    input: all_fasta="all_genes.fasta"
    output: aln="all_genes.aln"
    conda: "envs/phylo.yaml"
    shell: "mafft --auto {input.all_fasta} > {output.aln}"


rule trimal:
    input: aln="all_genes.aln"
    output: trm="all_genes.aln.trimmed"
    params: thr=config['trimal_threshold']
    conda: "envs/phylo.yaml"
    shell: """ trimal -in {input.aln} 
    	       	      -out {output.trm} 
		      -fasta 
		      -gt {params.thr} """

rule convert:
    input: trm="all_genes.aln.trimmed"
    output: phy="all_genes.aln.trimmed.phy"
    message: "Converting trimmed alignment to phy"
    shell: "python3 scripts/ETElib.py --alignment {input.trm}"


rule pythia:
    input: phy="all_genes.aln.trimmed.phy"
    output: "all_genes.aln.pythia.out"
    conda: "envs/phylo.yaml"
    shell: """ pythia --msa {input.phy} 
    	   	   -r raxml-ng 
		   --removeDuplicates 
		   -o {output} """


rule model_test:
    input: phy="all_genes.aln.trimmed.phy", pythia="all_genes.aln.pythia.out"
    output: "all_genes.trimmed.aln.phy.raxml.bestModel"
    params: type=config['type']
    conda: "envs/phylo.yaml"
    shell: """ modeltest-ng -i {input.phy} 
    	   		 -d {params.type} 
			 -t ml 
			 -c 
			 -T raxml """

rule raxml:
     input: pythia="all_genes.aln.pythia.out",
     	    modeltest="all_genes.trimmed.aln.phy.raxml.bestModel"
	    
     output: "all_genes.trimmed.aln.phy.raxml.support"
     threads: config['raxmlng_threads']
     conda: "envs/phylo.yaml"
     params: rtn=config['random_tree_number'],
     	     ptn=config['parsimony_tree_number'],
	     outgroup=config['outgroup']
	     
     shell: """ BEST_MODEL=$(sed 's/.\{{.*//g' all_genes.trimmed.aln.phy.raxml.bestModel) &&

     	        raxml-ng --all 
            		 --msa all_genes.aln.trimmed.phy 
			 --model $BEST_MODEL
			 --tree rand{{params.rtn}}, pars{{params.ptn}} 
			 --outgroup {params.outgroup} 
			 --threads {threads} 
			 --workers auto """

rule midpoint_root:
    input: "all_genes.trimmed.aln.phy.raxml.support"
    output: "all_genes.trimmed.aln.phy.raxml.support.midpoint_rooted"
    shell: """ python3 scripts/ETElib.py --tree {input} --midpoint """


rule visualize_tree:
    input: "all_genes.trimmed.aln.phy.raxml.support.midpoint_rooted"
    output: "all_genes.trimmed.aln.phy.raxml.support.midpoint_rooted.svg"
    shell: """ python3 scripts/ETElib.py --tree {input} --visualize """
