type: aa
trimal_threshold: 0.50
run_model_test_ng: False,
modeltest_threads: 20 # Threads to be given to ModelTest-NG if run_model_test_ng = True
substitution_model: 'LG+G4'
raxml_ng: 'raxml-ng-mpi' # Name of RAxML-NG executable
raxmlng_threads: 40
random_tree_number: 10
parsimony_tree_number: 90
outgroup: '' ## If this is an empty string, the tree is automatically midpoint-rooted